version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: hnyear-backend:latest
    container_name: hnyear_backend
    env_file:
      - .env
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_API_KEY_ANALYSIS=${GEMINI_API_KEY_ANALYSIS}
      - PORT=3001
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-*}
      - ROBOKASSA_LOGIN=${ROBOKASSA_LOGIN:-hnyear.com}
      - ROBOKASSA_PASSWORD1=${ROBOKASSA_PASSWORD1:-LUaP7t8lK2Wx1SUc1Oax}
      - ROBOKASSA_PASSWORD2=${ROBOKASSA_PASSWORD2:-XZ5g281nZGqZdvNPlV8E}
      - ROBOKASSA_IS_TEST=${ROBOKASSA_IS_TEST:-0}
      - ROBOKASSA_PAYMENT_AMOUNT=${ROBOKASSA_PAYMENT_AMOUNT:-100.00}
    restart: unless-stopped
    volumes:
      - ./data:/data
    networks:
      - newava_network  # Используем общую сеть с проектом newava

  app:
    build: .
    image: hnyear:latest
    container_name: hnyear_app
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    restart: unless-stopped
    networks:
      - newava_network  # Используем общую сеть с проектом newava

networks:
  newava_network:
    external: true  # Используем существующую сеть от проекта newava

